# 智付通測試平台: https://cwww.spgateway.com/
# 信用卡測試卡號: 4000-2211-2222-2222
 
default: &default
  merchant_id: MS365786496
  hash_key: ifGhmY7UIhbzJtcimLvHJA1PWMqe7oyI
  hash_iv: V23iRlNcatkQEmdf
  url: https://ccore.spgateway.com/MPG/mpg_gateway
  notify_url: http://requestbin.fullcontact.com/xrzi3wxs
  
development:
  <<: *default
 
staging:
  <<: *default
 
test:
  <<: *default
 
production:
  <<: *default